[build]
  command = "npm run build"
  publish = "src"  # Tentukan folder tempat file statis atau hasil build
  functions = "src/netlify/functions"  # Tempatkan fungsi di folder ini

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
